common:
  img_topic: "/left_camera/image"
  lid_topic: "/livox/lidar"
  imu_topic: "/livox/imu"
  img_en: 0
  lidar_en: 1
  ros_driver_bug_fix: false

extrin_calib:
  extrinsic_T: [-0.011, -0.02329, 0.04412]
  extrinsic_R: [1, 0, 0, 0, 1, 0, 0, 0, 1]
  Rcl: [ -0.002043, -0.999998,  0.000327,
        0.379870, -0.001079, -0.925039,
        0.925038, -0.001765,  0.379871]
  Pcl: [  0.017663, -0.087666,  0.033230]

time_offset:
  imu_time_offset: 0.0
  img_time_offset: 0.1
  exposure_time_init: 0.0

preprocess:
  point_filter_num: 1  # 每隔几个点取一个点处理
  filter_size_surf: 0.1 # 体素滤波设置 0.1m*0.1m*0.1m
  lidar_type: 1 # Livox Avia LiDAR
  scan_line: 4
  blind: 0.5 # 近处盲区半径 0.5m

vio:
  max_iterations: 5
  outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite
  img_point_cov: 100 # 100 1000
  patch_size: 8
  patch_pyrimid_level: 4
  normal_en: true
  raycast_en: false
  inverse_composition_en: false
  exposure_estimate_en: true
  inv_expo_cov: 0.1

imu:
  imu_en: true
  imu_int_frame: 30
  acc_cov: 0.8 # 0.2
  gyr_cov: 0.5 # 0.5
  b_acc_cov: 0.001 # 0.1
  b_gyr_cov: 0.001 # 0.1

lio:
  max_iterations: 5               # ESIKF 中的更新迭代次数
  dept_err: 0.02                  # 激光雷达的深度误差，0.02m
  beam_err: 0.15                  # 激光雷达的方向误差，0.15°
  min_eigen_value: 0.005 # 0.005  # 平面奇异值分解后的最小特征上限（阈值）
  voxel_size: 0.5                 # 系统先将每帧点云用 0.1*0.1*0.1m 的体素进行滤波，再用 0.5*0.5*0.5m 的体素划分地图。
  max_layer: 2                    # 八叉树的最大层数0-2
  max_points_num: 50              # 每个节点的最大存点量
  layer_init_num: [5, 5, 5, 5, 5] # 每个节点的最小存点量

local_map:
  map_sliding_en: false
  half_map_size: 100
  sliding_thresh: 8

uav:
  imu_rate_odom: false
  gravity_align_en: true

publish:
  dense_map_en: false # 是否发布当前帧未经0.1m体素降采样的稠密点云到 /cloud_register
  pub_effect_point_en: true # 是否发布当前帧成功匹配到平面的有效点云
  pub_plane_en: true # 是否发布拟合平面
  pub_scan_num: 1 # 仅在VIO模式下有效，决定多少次VIO更新后发布一次多帧累积的着色点云
  blind_rgb_points: 0.0

evo:
  seq_name: "CBD_Building_01"
  pose_output_en: false

pcd_save:
  pcd_save_en: false
  colmap_output_en: true # need to set interval = -1
  filter_size_pcd: 0.15
  interval: -1